# git
abbr -g g 'git'
abbr -g ga 'git add'
abbr -g gc 'git commit -sm'
abbr -g gcf 'git clean -df'
abbr -g gic 'git commit --allow-empty -sm "Initial commit"'
abbr -g gpmb 'git branch --merged | grep -v master | xargs -P (nproc) git branch -D'
abbr -g gr 'git reset --hard'
abbr -g grh 'git reset HEAD^1'
abbr -g gs 'git switch'
abbr -g gsc 'git switch -c'
abbr -g gss 'git status -s'
