# git
abbr g 'git'
abbr ga 'git add'
abbr gaa 'git add . -A'
abbr gc 'git commit -sm'
abbr gcf 'git clean -df'
abbr gic 'git commit --allow-empty -sm "Initial commit"'
abbr gl 'git log'
abbr gp 'git push'
abbr gpmb 'git branch --merged | grep -v master | xargs -P (nproc) git branch -D'
abbr gpo 'git pull origin'
abbr gr 'git reset --hard'
abbr grh 'git reset HEAD^1'
abbr grpo 'git remote prune origin'
abbr gs 'git status -s'
abbr gsc 'git switch -c'
abbr gt 'git tag -l'

# youtube-dl
abbr mp3dl 'youtube-dl -f mp3'
abbr mp4dl 'youtube-dl -f mp4'
