name: Main workflow

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install rcm for macOS
        run: |
          brew tap thoughtbot/formulae
          brew install rcm
        if: matrix.os == 'macos-latest'

      - name: Install rcm for Ubuntu
        run: |
          sudo add-apt-repository ppa:martin-frost/thoughtbot-rcm
          sudo apt-get update
          sudo apt-get install rcm
        if: matrix.os == 'ubuntu-latest'

      - name: Install the dotfiles
        env:
          RCRC: $GITHUB_WORKSPACE/rcrc
        run: rcup
