name: Main workflow

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Install rcm
        run: |
          brew tap thoughtbot/formulae
          brew install rcm

      - name: Install the dotfiles
        env:
          RCRC: $GITHUB_WORKSPACE/rcrc
        run: rcup
